@extends('layouts.app')

@section('title', 'Manage content')

@section('content')
<div class="page-header">
    <h1>Manage content</h1>
    <p class="lead">Choose a section to manage creatures, items, or travel suggestions.</p>
</div>

<style>
    .content-hub-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1.25rem; }
    .content-hub-card {
        background: var(--surface);
        border: 1px solid var(--border);
        border-radius: var(--radius);
        padding: 1.25rem;
        box-shadow: var(--shadow);
        transition: border-color 0.15s, box-shadow 0.15s;
    }
    .content-hub-card:hover { border-color: var(--accent); box-shadow: var(--shadow-lg); }
    .content-hub-card h3 { font-size: 1.125rem; margin: 0 0 0.5rem 0; }
    .content-hub-card p { font-size: 0.9375rem; color: var(--text-secondary); margin: 0 0 1rem 0; line-height: 1.5; }
    .content-hub-card a.btn { display: inline-block; padding: 0.4rem 0.85rem; background: var(--accent); color: white; text-decoration: none; border-radius: var(--radius-sm); font-weight: 500; font-size: 0.9375rem; }
    .content-hub-card a.btn:hover { background: var(--accent-hover); }
</style>

<div class="content-hub-grid">
    @if($canManageCreatures)
    <div class="content-hub-card">
        <h3>Creatures</h3>
        <p>Archive creatures and their stages. Add, edit, or remove creatures.</p>
        <a href="{{ route('content.creature.index') }}" class="btn">Manage creatures</a>
    </div>
    @endif
    @if($canManageItems)
    <div class="content-hub-card">
        <h3>Items</h3>
        <p>Item catalog (travels, trinkets, etc.). Add, edit, or remove items.</p>
        <a href="{{ route('content.item.index') }}" class="btn">Manage items</a>
    </div>
    @endif
    @if($canManageTravelSuggestions)
    <div class="content-hub-card">
        <h3>Travel suggestions</h3>
        <p>Suggest which travel items go with specific creature stages.</p>
        <a href="{{ route('content.travel-suggestions.index') }}" class="btn">Manage travel suggestions</a>
    </div>
    @endif
    @if($canManagePendingAi)
    <div class="content-hub-card">
        <h3>Pending image-based suggestions</h3>
        <p>Approve or reject travel suggestions from the image-match job@if(auth()->user()->isAdmin()) (run <code>travels:suggest-by-image</code> from the admin to generate)@else (generated by an admin when they run the image-match job)@endif.</p>
        <a href="{{ route('content.pending-ai-travel-suggestions.index') }}" class="btn">Pending travel suggestions</a>
    </div>
    @endif
</div>

@if($canAccessAdmin)
<p style="margin-top: 1.5rem;"><a href="{{ route('admin') }}">← Back to admin</a></p>
@endif
@endsection
