@extends('layouts.app')

@section('title', 'Pending travel suggestions (image match)')

@section('content')
<div class="page-header">
    <h1>Pending travel suggestions (image match)</h1>
    <p class="lead">Approve or reject image-based travel suggestions (up to 5 per creature). Approved suggestions are added to all stages of that creature.</p>
</div>

<style>
    .content-table { width: 100%; border-collapse: collapse; background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); overflow: hidden; box-shadow: var(--shadow); }
    .content-table th, .content-table td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid var(--border); }
    .content-table th { background: var(--bg); font-weight: 600; font-size: 0.875rem; color: var(--text-secondary); }
    .content-table tr:last-child td { border-bottom: none; }
    .content-table a { color: var(--accent); font-weight: 500; }
    .content-table a:hover { text-decoration: underline; }
    .content-actions { display: flex; gap: 0.5rem; flex-wrap: wrap; }
    .content-actions form { margin: 0; }
    .btn-sm { padding: 0.25rem 0.5rem; font-size: 0.8125rem; border-radius: var(--radius-sm); cursor: pointer; font-family: inherit; text-decoration: none; display: inline-block; border: 1px solid var(--border); background: var(--surface); color: var(--text); }
    .btn-sm:hover { border-color: var(--accent); color: var(--accent); }
    .btn-approve { border-color: #22c55e; color: #22c55e; }
    .btn-approve:hover { background: #f0fdf4; }
    .btn-reject { border-color: #dc2626; color: #dc2626; }
    .btn-reject:hover { background: #fef2f2; }
    .creature-group { margin-bottom: 1.5rem; }
    .creature-group h3 { font-size: 1rem; margin: 0 0 0.5rem 0; }
    .pending-previews-row { display: flex; gap: 0.5rem; flex-wrap: wrap; align-items: flex-start; }
    .pending-preview-wrap { text-align: center; }
    .pending-preview-wrap .stage-label { font-size: 0.65rem; color: var(--text-secondary); margin-top: 0.2rem; }
    .pending-preview { position: relative; width: 64px; height: 64px; flex-shrink: 0; border-radius: var(--radius-sm); overflow: hidden; border: 1px solid var(--border); }
    .pending-preview .preview-bg { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; z-index: 1; }
    .pending-preview .preview-creature { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: contain; z-index: 2; }
</style>

<p style="font-size: 0.9375rem; color: var(--text-secondary); margin-bottom: 1rem;">Suggestions are generated by the <code>travels:suggest-by-image</code> command (run from Dashboard → Run jobs manually).</p>

@if($pendingByCreature->isEmpty())
    <p style="color: var(--text-secondary); font-size: 0.9375rem;">No pending suggestions. Run <code>travels:suggest-by-image</code> from the dashboard (free, image-based).</p>
@else
    @foreach($pendingByCreature as $archiveItemId => $pendingList)
        @php
            $creature = $pendingList->first()->archiveItem;
        @endphp
        <div class="creature-group">
            <h3>
                <a href="{{ route('archive.show', $creature->slug) }}">{{ $creature->title }}</a>
            </h3>
            <table class="content-table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Preview — all stages (creature on top + travel)</th>
                        <th>Travel</th>
                        <th style="width: 14rem;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($pendingList as $pending)
                        @php
                            $travelItem = $pending->item;
                            $stages = $creature->stages->take(4);
                        @endphp
                        <tr>
                            <td>{{ $pending->sort_order }}</td>
                            <td>
                                <div class="pending-previews-row">
                                    @foreach($stages as $creatureStage)
                                        <div class="pending-preview-wrap">
                                            <div class="pending-preview">
                                                @if($travelItem->image_url)
                                                    <img class="preview-bg" src="{{ $travelItem->image_url }}" alt="" referrerpolicy="no-referrer">
                                                @endif
                                                @if($creatureStage->image_url)
                                                    <img class="preview-creature" src="{{ $creatureStage->image_url }}" alt="" referrerpolicy="no-referrer">
                                                @endif
                                            </div>
                                            <div class="stage-label">Stage {{ $creatureStage->stage_number }}</div>
                                        </div>
                                    @endforeach
                                </div>
                            </td>
                            <td>
                                <a href="{{ route('items.show', $pending->item->slug) }}">{{ $pending->item->name }}</a>
                            </td>
                            <td>
                                <div class="content-actions">
                                    <form method="post" action="{{ route('content.pending-ai-travel-suggestions.approve', $pending) }}">
                                        @csrf
                                        <button type="submit" class="btn-sm btn-approve">Approve</button>
                                    </form>
                                    <form method="post" action="{{ route('content.pending-ai-travel-suggestions.reject', $pending) }}" onsubmit="return confirm('Reject this suggestion?');">
                                        @csrf
                                        <button type="submit" class="btn-sm btn-reject">Reject</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endforeach
@endif

<p style="margin-top: 1.5rem;"><a href="{{ route('content.index') }}">← Back to manage content</a></p>
@endsection
